apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          image: leeyoongti/node-web-app-1:latest
          ports:
            - containerPort: 3000
          env:
            - name: REQUEST_ADDRESS
              value: app-2-service